### ISSUE TITLE
Problem while installing dependencies

### ISSUE THREAD

**Issue by rijkerd** [ATF19/react-native-shop-ui#13]
![screenshot from 2018-07-10 17-59-43](https://user-images.githubusercontent.com/18520338/42518697-227f5b74-846b-11e8-8029-794aa2dbec53.png)
Any help please.

**Comment by ATF19** [comment]
Hello,

I am not seeing any errors in the console, please try running the app and see if it does works.

**Comment by rijkerd** [comment]
I was running npm install on the project and it stops over there tried more than three times
